name: flutter_web_portfolio
description: A Flutter web portfolio with BLoC and custom animations.
publish_to: 'none'

environment:
  sdk: 3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  animated_text_kit: ^4.2.3
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
